language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
script: ./node_modules/.bin/grunt publish
env:
  global:
  - secure: Ab6jf3s9srHxwH81gsJZgh3DW+TtiupaoTnoxXc2430mvQL7xVGuTV/uacpmOcZSUTNdE7j92b8bV9zG8qCAwwAvo30OdaIb+ez704bjc2lFjPnkoIA8ZSWLgOa+990aIbKGQTurA6IEnUsm1WDVl/YoixSQj5Ij3l5tIti43+8=
